# Generated by Django 5.2 on 2025-04-24 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dmsapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='storeasuser',
            old_name='storeName',
            new_name='store_name',
        ),
        migrations.RenameField(
            model_name='storeasuser',
            old_name='storeNumber',
            new_name='store_number',
        ),
    ]
