# Generated by Django 5.2 on 2025-04-25 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmsapp', '0002_rename_storename_storeasuser_store_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storeasuser',
            name='password',
            field=models.CharField(max_length=100),
        ),
    ]
