# Generated by Django 5.2 on 2025-04-25 20:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmsapp', '0003_alter_storeasuser_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cooler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Door',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shelves', models.IntegerField()),
                ('slots', models.IntegerField()),
                ('cooler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dmsapp.cooler')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dmsapp.type')),
            ],
        ),
    ]
