# Generated by Django 5.2 on 2025-04-28 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmsapp', '0004_cooler_type_door'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeasuser',
            name='coolers',
            field=models.ManyToManyField(related_name='stores', to='dmsapp.cooler'),
        ),
    ]
